### ISSUE TITLE
How can I use this in monorepo?

### ISSUE THREAD

**Issue by nacal** [ysk8hori/delta-typescript-graph-action#164]
I find this workflow very impressive, and I’d like to use it in a monorepo project. However, I haven’t been able to make it work as expected. Here’s what I’ve tried so far:

```
.github
    ┗ workflows
    　　┗ workflow.yml
 my-app
     ┣ tsconfig.json
     ┗ (other files...)
```

```yml
on: pull_request

permissions:
  pull-requests: write

jobs:
  delta-typescript-graph-job:
    runs-on: ubuntu-latest
    name: Delta TypeScript Graph
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ysk8hori/delta-typescript-graph-action@v1.0.5
        with:
          tsconfig-root: './my-app'
          debug: true
```

log
```
[
  {
    "filename": "my-app/src/app/layout.tsx",
    "status": "modified"
  },
  {
    "filename": "my-app/src/app/page.tsx",
    "status": "modified"
  }
]
modified: [
  {
    "filename": "my-app/src/app/layout.tsx",
    "status": "modified"
  },
  {
    "filename": "my-app/src/app/page.tsx",
    "status": "modified"
  }
]
created: []
deleted: []
renamed: []
From https://github.com/nacal/delta-typescript-graph-test
 * branch            e8186296a59d2545a18e0975c3271c93cb195458 -> FETCH_HEAD
Previous HEAD position was a7921f2 Merge e8186296a59d2545a18e0975c3271c93cb195458 into ad94cff7bbef08806da9ec56d14857e5a50e2f58
HEAD is now at e818629 debug
fullHeadGraph.nodes.length: 3
fullHeadGraph.relations.length: 0
From https://github.com/nacal/delta-typescript-graph-test
 * branch            ad94cff7bbef08806da9ec56d14857e5a50e2f58 -> FETCH_HEAD
Warning: you are leaving 5 commits behind, not connected to
any of your branches:

  e818629 debug
  bc91e5f tsconfig-root
  f5d8bc1 fix dir
  2b6df[12](https://github.com/nacal/delta-typescript-graph-test/actions/runs/12238076373/job/34135296671?pr=1#step:3:13) commit
  23aedd1 create workflow

If you want to keep them by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> e8[18](https://github.com/nacal/delta-typescript-graph-test/actions/runs/12238076373/job/34135296671?pr=1#step:3:19)629

HEAD is now at ad94cff init
fullBaseGraph.nodes.length: 3
fullBaseGraph.relations.length: 0
fullBaseGraph.nodes.length: 3
fullBaseGraph.relations.length: 0
fullHeadGraph.nodes.length: 3
fullHeadGraph.relations.length: 0
meta: {
  "rootDir": "/home/runner/work/delta-typescript-graph-test/delta-typescript-graph-test/my-app"
}
createdRelations: []
deletedRelations: []
mergedGraph.nodes.length: 3
mergedGraph.relations.length: 0
includes: [
  "my-app/src/app/layout.tsx",
  "my-app/src/app/page.tsx"
]
abstractionTarget: [
  "src/app"
]
filteredGraph.nodes.length: 0
filteredGraph.relations.length: 0
abstractedGraph.nodes.length: 0
abstractedGraph.relations.length: 0
graph.nodes.length: 0
graph.relations.length: 0
The graph is empty.
```

Specifically, this workflow seems to create an empty graph, which shouldn’t be the case.

The tsc command being executed appears to be:

```
tsc --include my-app/app/layout.tsx my-app/app/page.tsx
```

I suspect the issue lies in the path, as it resolves to my-app/src/app/layout.tsx from the project root. This might be causing the problem.

If you could provide guidance or suggest any fixes, I would greatly appreciate it. Thank you for this amazing workflow!
